[project]
name = "extensions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Aidan Morgan", email = "aidan.j.morgan@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[tool.uv.sources]
core = { workspace = true }
game = {workspace = true}


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
